services:
  - type: web
    name: pharmastic-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: WHATSAPP_TOKEN
        sync: false
      - key: PHONE_NUMBER_ID
        sync: false
      - key: VERIFY_TOKEN
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: MONGODB_URL
        sync: false
      - key: DATABASE_NAME
        value: pharmastic_bot
